name: khodecamp
description: The KhodeCamp app showcases the KhodeCamp platform.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  flutter_gen: any
  firebase_core: ^2.27.2
  firebase_messaging: ^14.7.21
  firebase_analytics: ^10.9.0

  bloc: ^8.1.3
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  upgrader: ^10.3.0
  http: ^1.2.1
  package_info_plus: ^6.0.0


dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
